"""
Alert model for system alerts and notifications.

Stores alerts generated by agents or the system, including fire warnings,
PSPS notifications, and sensor anomalies.
"""

from datetime import datetime
from typing import Optional, TYPE_CHECKING
from uuid import UUID

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship
import enum

from app.models.base import BaseModel


class AlertSeverity(str, enum.Enum):
    """Enumeration of alert severity levels."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    WARNING = "WARNING"  # Amber/amber alerts (added for Agent 2)
    INFO = "INFO"  # Blue/informational alerts (added for Agent 2)


class AlertType(str, enum.Enum):
    """Enumeration of alert types/categories."""

    IRRIGATION_RECOMMENDED = "irrigation"
    PSPS_WARNING = "psps_warning"
    PSPS_ACTIVE = "psps_active"
    WATER_SAVED_MILESTONE = "water_saved"
    FIRE_RISK_WARNING = "fire_risk"


class AgentType(str, enum.Enum):
    """Enumeration of agent types that generate alerts."""

    FIRE_ADAPTIVE_IRRIGATION = "FIRE_ADAPTIVE_IRRIGATION"
    WATER_EFFICIENCY = "WATER_EFFICIENCY"
    PSPS_ANTICIPATION = "PSPS_ANTICIPATION"
    SYSTEM = "SYSTEM"  # System-generated alerts


class Alert(BaseModel):
    """
    System alert model.

    Represents an alert generated by an agent or the system,
    such as fire warnings, PSPS notifications, or sensor anomalies.
    """

    __tablename__ = "alerts"

    # Foreign key to field (nullable for system-wide alerts)
    field_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("fields.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )

    # Agent information
    agent_type: Mapped[AgentType] = mapped_column(
        SQLEnum(AgentType),
        nullable=False,
        index=True,
        comment="Type of agent that generated this alert",
    )

    # Alert type/category
    alert_type: Mapped[AlertType] = mapped_column(
        SQLEnum(AlertType),
        nullable=False,
        index=True,
        comment="Category/type of alert (irrigation, psps_warning, etc.)",
    )

    # Alert details
    severity: Mapped[AlertSeverity] = mapped_column(
        SQLEnum(AlertSeverity),
        nullable=False,
        index=True,
        comment="Alert severity level (CRITICAL=red, WARNING=amber, INFO=blue)",
    )
    message: Mapped[str] = mapped_column(Text, nullable=False)

    # Status
    acknowledged: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        index=True,
        comment="Whether the alert has been acknowledged by the user",
    )
    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="When the alert was acknowledged",
    )

    # Relationship
    field: Mapped[Optional["Field"]] = relationship(
        "Field", back_populates="alerts"
    )

    def __repr__(self) -> str:
        """String representation of the alert."""
        return (
            f"<Alert(id={self.id}, type={self.alert_type.value}, "
            f"severity={self.severity.value}, agent={self.agent_type.value}, "
            f"acknowledged={self.acknowledged})>"
        )

